name: Validate

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Check PEP8
        uses: andymckay/pycodestyle-action@0.1.3

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

      - name: HASSFEST
        uses: home-assistant/actions/hassfest@master
